const jogadores = [
    {
        posicao: "goleiro", 

        jogadoresPosicao: [
            {
                nome: "Alisson",
                overall: 91,
                time: "Liverpool",
                liga: "prl",
                pais: "BR",
                foto: "https://ratings-images-prod.pulse.ea.com/FC25/full/player-portraits/p212831.png?padding=0.7",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452"
            },
            {
                nome: "Neuer",
                overall: 88,
                time: "Bayern",
                liga: "bun",
                pais: "DE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/167495.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=843ea056bd21de97ad1c7d797c7448df",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/1024px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png",
            },
            {
                nome: "Martinez",
                overall: 86,
                time: "Aston Villa",
                liga: "prl",
                pais: "AR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/202811.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=7085a21d2bdfc5d92047e8e54025fc70",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/2/29/Aston_Villa_FC_2024_logo.png",
            },
            {
                nome: "Courtois",
                overall: 91,
                time: "Real Madrid",
                liga: "lal",
                pais: "BE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/192119.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=9e2b685d49d90c141b63266865d980dd",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Ter Stegen",
                overall: 87,
                time: "Barcelona",
                liga: "lal",
                pais: "DE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/192448.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=1b3f7a672fee3ec0dd4fdff0ed0bdc17",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Oblak",
                overall: 90,
                time: "Atletico Madrid",
                liga: "lal",
                pais: "SI",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/200389.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=71d94a2a6bb981c537eb69d215902737",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/1/19/AtleticoMadrid2017.png",
            },
            {
                nome: "Donnaruma",
                overall: 90,
                time: "Man City",
                liga: "prl",
                pais: "IT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/230621.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=589b7d85cdb178ec8f9f4d7b4d9b5215",
                timeimg: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
            },
            {
                nome: "Kobel",
                overall: 85,
                time: "Dortmund",
                liga: "bun",
                pais: "CH",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/235073.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=aa118437b5e532f53960b484169ea546",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/2048px-Borussia_Dortmund_logo.svg.png",
            },
            {
                nome: "Sommer",
                overall: 85,
                time: "Inter",
                liga: "sra",
                pais: "CH",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/177683.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=a8b084faa61a09b84054fc7627a9657a",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/2048px-FC_Internazionale_Milano_2021.svg.png",
            },
            {
                nome: "Mamardashvilli",
                overall: 88,
                time: "Liverpool",
                liga: "prl",
                pais: "GE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/262621.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=4429a46b091760b4b35d07648006a7e3",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452",
            },
            {
                nome: "Vicario",
                overall: 88,
                time: "Tottenham",
                liga: "prl",
                pais: "IT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/240091.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=bcc4a7ab46d9bbe71632b334e827afc6",
                timeimg: "https://images.seeklogo.com/logo-png/55/2/tottenham-hotspur-f-c-2024-logo-png_seeklogo-557792.png",
            },
            {
                nome: "Raya",
                overall: 86,
                time: "Arsenal",
                liga: "prl",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/220901.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=65586ceeb04ad540e6a305ea52441ac9",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
            {
                nome: "Unai Simon",
                overall: 84,
                time: "Bilbao",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/230869.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=8e3b3ad002c63d0039cb6ef233910f4f",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/90/Athletic_Club_de_Bilbao.png",
            },
            {
                nome: "Lunin",
                overall: 83,
                time: "Real Madrid",
                liga: "lal",
                pais: "UA",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/243952.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=3bc7b2a925e1f5698c01094d67fd8c72",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Pickford",
                overall: 84,
                time: "Everton",
                liga: "prl",
                pais: "GB",
                uk: "inglaterra",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/204935.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=41e0d9546a175e960a9a3b60b918bf9b",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/a/ae/Everton_FC_logo_2014.png",
            },
            
        ]


    },


    {
        posicao: "zagueiro", 

        jogadoresPosicao: [
            {
                nome: "Cubarsi",
                overall: 89,
                time: "Barcelona",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/278046.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=0aef0cfa3b4fb1d61b9afa6fdf76ee9b",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Araujo",
                overall: 88,
                time: "Barcelona",
                liga: "lal",
                pais: "UY",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/253163.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=cdf3c7e6542606572596f69182085fe5",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Huijsen",
                overall: 87,
                time: "Real Madrid",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/278349.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=eef509785ed396aa29eae8cd12e6ca29",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Rudiger",
                overall: 88,
                time: "Real Madrid",
                liga: "lal",
                pais: "DE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/205452.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=0a99debe47bf1795503c25cee01fe7e9",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Gvardiol",
                overall: 88,
                time: "Man City",
                liga: "prl",
                pais: "HR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/251517.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=c5a03eeae4df1191f14976153b6c0e13",
                timeimg: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
            },
            {
                nome: "Pacho",
                overall: 86,
                time: "Paris",
                liga: "li1",
                pais: "CO",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/256196.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=d54aefbed2b917571011a52a5ea0eab3",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png",
            },
            {
                nome: "Pavard",
                overall: 85,
                time: "Inter",
                liga: "sra",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/226851.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=0be5dce178283719daa6ace9a8784f9f",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/2048px-FC_Internazionale_Milano_2021.svg.png",
            },
            {
                nome: "Bastoni",
                overall: 87,
                time: "Inter",
                liga: "sra",
                pais: "IT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/237383.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=c2add97036fb31c3699e3e755ecbd499",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/2048px-FC_Internazionale_Milano_2021.svg.png",
            },
            {
                nome: "Van Dijk",
                overall: 91,
                time: "Liverpool",
                liga: "prl",
                pais: "NL",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/203376.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=2b9ae4559efb08e77d2bc18b1af3e77d",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452",
            },
            {
                nome: "Tah",
                overall: 87,
                time: "Bayern",
                liga: "bun",
                pais: "DE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/213331.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=1770053494264868618bd864c3bbd843",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/1024px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png",
            },
            {
                nome: "Marquinhos",
                overall: 87,
                time: "Paris",
                liga: "li1",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/207865.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=1c9f06a9b472f342318d511f367dec8c",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png",
            },
            {
                nome: "Saliba",
                overall: 88,
                time: "Arsenal",
                liga: "prl",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/243715.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=01a31c97351b50ee2bdf8f9fc7ae14db",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
            {
                nome: "Ruben Dias",
                overall: 90,
                time: "Man City",
                liga: "prl",
                pais: "PT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/239818.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=c9e79045ef90edb7ccbacfd2296f41c5",
                timeimg: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
            },
            {
                nome: "Van De Ven",
                overall: 84,
                time: "Tottenham",
                liga: "prl",
                pais: "NL",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/264453.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=0d1637b142b351396d3d4092e02369e1",
                timeimg: "https://images.seeklogo.com/logo-png/55/2/tottenham-hotspur-f-c-2024-logo-png_seeklogo-557792.png",
            },
            {
                nome: "Romero",
                overall: 90,
                time: "Tottenham",
                liga: "prl",
                pais: "AR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/232488.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=2fdd4f5bceae06a73b8bbdb15e0a5904",
                timeimg: "https://images.seeklogo.com/logo-png/55/2/tottenham-hotspur-f-c-2024-logo-png_seeklogo-557792.png",
            },
            {
                nome: "Upamecano",
                overall: 86,
                time: "Bayern",
                liga: "bun",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/229558.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=cdda4df345d5c445bd309646e02f118e",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/1024px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png",
            },
            {
                nome: "Kim Min Jae",
                overall: 87,
                time: "Bayern",
                liga: "bun",
                pais: "KR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/237086.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=f8bf48600713162ab02461f68b2d770a",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/1024px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png",
            },
            {
                nome: "Dante",
                overall: 79,
                time: "Nice",
                liga: "li1",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa25/img/players/158625.png?fm=png&ixlib=java-2.1.0&verzion=2&w=162&s=0fcc8eec7c5753f38c899f041014e08a",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/d/d2/OGC_Nice.svg/1658px-OGC_Nice.svg.png",
            },
            {
                nome: "Hummels",
                overall: 84,
                time: "Roma",
                liga: "sra",
                pais: "DE",
                foto: "https://cdn3.futbin.com/content/fifa25/img/players/178603.png?fm=png&ixlib=java-2.1.0&w=162&s=2d828a745f6f5219defeded2420f3f2f",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/8/8c/AS_Roma_logo.png",
            },
            {
                nome: "Gimenez",
                overall: 88,
                time: "Atletico Madrid",
                liga: "lal",
                pais: "UY",
                foto: "https://cdn3.futbin.com/content/fifa25/img/players/216460.png?fm=png&ixlib=java-2.1.0&verzion=2&w=512&s=de814de29903909f64bebbe31c90beee",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/1/19/AtleticoMadrid2017.png",
            },
        ]


    },
    {
        posicao: "lateral", 

        jogadoresPosicao: [
            {
                nome: "Hakimi",
                overall: "91",
                time: "Paris",
                liga: "li1",
                pais: "MA",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/235212.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=ae045bef30cbf503b24b67184bb6f541",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png",
            },
            {
                nome: "Kounde",
                overall: "88",
                time: "Barcelona",
                liga: "lal",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/241486.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=12cc32f80b5aa8f5ee7ec538d3df51ae",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Trent",
                overall: "86",
                time: "Real Madrid",
                liga: "lal",
                pais: "GB",
                uk: "inglaterra",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/231281.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=940877a720713272e1f03c040063a84a",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Carvajal",
                overall: "83",
                time: "Real Madrid",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/204963.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=9771e7abfedaf4ce1828b22d2ec4aa11",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Llorente",
                overall: "86",
                time: "Atletico Madrid",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/226161.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=32dec767c7a3d03bb75b5eac6629d1d4",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/1/19/AtleticoMadrid2017.png",
            },
            {
                nome: "Frimpong",
                overall: "86",
                time: "Liverpool",
                liga: "prl",
                pais: "NL",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/253149.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=564f560c1b2ba4c417e12713d0429dc7",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452",
            },
            {
                nome: "Di Lorenzo",
                overall: "83",
                time: "Napoli",
                liga: "sra",
                pais: "IT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/217870.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=6cc1e83db32a622cc7708327ac03e71b",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/SSC_Napoli.svg/2048px-SSC_Napoli.svg.png",
            },
            {
                nome: "Nuno Mendes",
                overall: "90",
                time: "Paris",
                liga: "li1",
                pais: "PT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/252145.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=74ccd18a5a7c9abbaec88b3cd51b82da",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png",
            },
            {
                nome: "Dimarco",
                overall: "87",
                time: "Inter",
                liga: "sra",
                pais: "IT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/226268.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=b5442c850377bdda63a33accc168b782",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/2048px-FC_Internazionale_Milano_2021.svg.png",
            },
            {
                nome: "Davies",
                overall: "86",
                time: "Bayern",
                liga: "bun",
                pais: "CA",
                foto: "https://cdn3.futbin.com/content/fifa25/img/players/234396.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=081ef58cb2fdc83875c53e4219b7b747",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/1024px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png",
            },
            {
                nome: "Cucurella",
                overall: "85",
                time: "Chelsea",
                liga: "prl",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa25/img/players/239231.png?fm=png&ixlib=java-2.1.0&verzion=2&w=512&s=77f671b934e5fdf61831b0f5dfc68b03",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/c/cc/Chelsea_FC.svg/2048px-Chelsea_FC.svg.png",
            },
            {
                nome: "Robertson",
                overall: "84",
                time: "Liverpool",
                liga: "prl",
                pais: "GB",
                uk: "escocia",
                foto: "https://cdn3.futbin.com/content/fifa25/img/players/216267.png?fm=png&ixlib=java-2.1.0&verzion=2&w=512&s=7aca9d6a732499653a2844771b287c97",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452",
            },
            {
                nome: "Balde",
                overall: "86",
                time: "Barcelona",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/263578.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=61785a7c4ac8c71980881c67830dff24",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Theo Hernandez",
                overall: "86",
                time: "Milan",
                liga: "sra",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa24/img/players/232656.png?fm=png&ixlib=java-2.1.0&w=512&s=dc6abc9d2b7ced6e67cd1ad786a45808",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/1306px-Logo_of_AC_Milan.svg.png",
            },
            {
                nome: "Ake",
                overall: "85",
                time: "Man City",
                liga: "prl",
                pais: "NL",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/208920.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=8c8864a3626287abf4d1a5be1baebf19",
                timeimg: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
            },
            {
                nome: "Grimaldo",
                overall: "85",
                time: "Leverkusen",
                liga: "bun",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/210035.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=29b7aff61d6e7a9cb892fbb1a3e5e588",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/a/a2/Bayer_Leverkusen.png",
            },
            {
                nome: "Calafiori",
                overall: "85",
                time: "Arsenal",
                liga: "prl",
                pais: "IT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/257711.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=837670f5a656fcf7226c2f705f478e7d",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
        ]


    },
    {
        posicao: "volante",
        
        jogadoresPosicao: [
            {
                nome: "Kimmich",
                overall: "90",
                time: "Bayern",
                liga: "bun",
                pais: "DE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/212622.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=2abdeeb90342eb32cd5cd575accd5492",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/1024px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png",
            },
            {
                nome: "Rodri",
                overall: "90",
                time: "Man City",
                liga: "prl",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/231866.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=ff7d441715124eac277df8961f6f78fc",
                timeimg: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
            },
            {
                nome: "Rice",
                overall: "89",
                time: "Arsenal",
                liga: "prl",
                pais: "GB",
                uk: "inglaterra",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/234378.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=6d6680f97d81e90295cee7633f7e52e0",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
            {
                nome: "Caicedo",
                overall: "88",
                time: "Chelsea",
                liga: "prl",
                pais: "EC",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/256079.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=4d2761a215deda4a3a86264fe8a7bc89",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/c/cc/Chelsea_FC.svg/2048px-Chelsea_FC.svg.png",
            },
            {
                nome: "Calhanoglu",
                overall: "83",
                time: "Inter",
                liga: "sra",
                pais: "TR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/208128.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=0f0f5f5ca4cf6a3a957baa5601404946",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/2048px-FC_Internazionale_Milano_2021.svg.png",
            },
            {
                nome: "Tonali",
                overall: "86",
                time: "Newcastle",
                liga: "prl",
                pais: "IT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/241096.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=b746053e2cfd5c4b04d89d61526c494a",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/2/25/Newcastle_United_Logo.png",
            },
            {
                nome: "Gravenberch",
                overall: "85",
                time: "Liverpool",
                liga: "prl",
                pais: "NL",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/246104.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=9041863aad638019c7277ef0f4ce78b2",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452",
            },
            {
                nome: "Xhaka",
                overall: "82",
                time: "Sunderland",
                liga: "prl",
                pais: "CH",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/199503.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=c7398c41084b303433e9a4f8feaa651c",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/0/01/Sunderland_AFC.png",
            },
            {
                nome: "Tchouameni",
                overall: "86",
                time: "Real Madrid",
                liga: "lal",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/241637.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=a1c095ebf0b20e983195adcde7941928",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Camavinga",
                overall: "86",
                time: "Real Madrid",
                liga: "lal",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/248243.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=4ca16009e51742a55fe741e622040099",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Gavi",
                overall: "87",
                time: "Barcelona",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/264240.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=2ab70e56fdd2172b106ac5013ef83026",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Palhinha",
                overall: "84",
                time: "Tottenham",
                liga: "prl",
                pais: "PT",
                foto: "https://cdn3.futbin.com/content/fifa23/img/players/229391.png?fm=png&ixlib=java-2.1.0&w=512&s=eaf5b3281326df7f2b072dc0a537dd93",
                timeimg: "https://images.seeklogo.com/logo-png/55/2/tottenham-hotspur-f-c-2024-logo-png_seeklogo-557792.png",
            },
            {
                nome: "Casemiro",
                overall: "85",
                time: "Man United",
                liga: "prl",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/200145.png?fm=png&ixlib=java-2.1.0&w=162&s=b2d74001bf3960edbc99fb72aa9bc695",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/b/b6/Manchester_United_FC_logo.png",
            },
            {
                nome: "Bruno Guimaraes",
                overall: "87",
                time: "Newcastle",
                liga: "prl",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/247851.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=206d41e096f1f2cd1a0edaa160758881",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/2/25/Newcastle_United_Logo.png",
            },
            {
                nome: "De Jong",
                overall: "86",
                time: "Barcelona",
                liga: "lal",
                pais: "NL",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/228702.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=01501174369d5adb1516d6938332b4aa",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Valverde",
                overall: "89",
                time: "Real Madrid",
                liga: "lal",
                pais: "UY",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/239053.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=151e382bedeea810e516217ee1ee5811",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
        ]
    },
    {
        posicao: "meiocampo", 

        jogadoresPosicao: [
            {
                nome: "Vitinha",
                overall: "91",
                time: "Paris",
                liga: "li1",
                pais: "PT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/255253.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=fb451db77a67c61ded6124f251dbfd70",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png",
            },
            {
                nome: "Pedri",
                overall: "91",
                time: "Barcelona",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/251854.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=9e81187f04f317170559987bda3227c6",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "De Bruyne",
                overall: "90",
                time: "Napoli",
                liga: "sra",
                pais: "BE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/192985.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=b2e4eb2fc2a2946badaf1d25c31aa5d6",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/SSC_Napoli.svg/2048px-SSC_Napoli.svg.png",
            },
            {
                nome: "Mac Allister",
                overall: "89",
                time: "Liverpool",
                liga: "prl",
                pais: "AR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/239837.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=915211b72e1c0940c9ef2419a017c668",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452",
            },
            {
                nome: "Odegaard",
                overall: "89",
                time: "Arsenal",
                liga: "prl",
                pais: "NO",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/222665.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=5a5543c069f19369ca5edabdb98d6778",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
            {
                nome: "McTominay",
                overall: "89",
                time: "Napoli",
                liga: "sra",
                pais: "GB",
                uk: "escocia",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/237238.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=1e70806731f72fb9d69d26e24b031fb5",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/SSC_Napoli.svg/2048px-SSC_Napoli.svg.png",
            },
            {
                nome: "Joao Neves",
                overall: "88",
                time: "Paris",
                liga: "li1",
                pais: "PT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/272834.png?fm=png&ixlib=java-2.1.0&w=512&s=832dc8d53abc1f411c0801085624b473",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png",
            },
            {
                nome: "Bernardo Silva",
                overall: "87",
                time: "Man City",
                liga: "prl",
                pais: "PT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/218667.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=e4e3b32ba17a8c3543c788b9519b2b42",
                timeimg: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
            },
            {
                nome: "Modric",
                overall: "86",
                time: "Milan",
                liga: "sra",
                pais: "HR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/177003.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=4aa75d378a4579fabb556c53bf9bd6c3",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/1306px-Logo_of_AC_Milan.svg.png",
            },
            {
                nome: "Goretzka",
                overall: "88",
                time: "Bayern",
                liga: "bun",
                pais: "DE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/209658.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=186853b5842d017de6d1f546542a6e92",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/1024px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png",
            },
            {
                nome: "Gallagher",
                overall: "84",
                time: "Atletico Madrid",
                liga: "lal",
                pais: "GB",
                uk: "inglaterra",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/238216.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=782ff2366ca8a5e922facb17db6afc13",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/1/19/AtleticoMadrid2017.png",
            },
            {
                nome: "Griezmann",
                overall: "86",
                time: "Atletico Madrid",
                liga: "lal",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/194765.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=0e6dd38f4ce34f833cd937a0d53277de",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/1/19/AtleticoMadrid2017.png",
            },
            {
                nome: "Bellingham",
                overall: "90",
                time: "Real Madrid",
                liga: "lal",
                pais: "GB",
                uk: "inglaterra",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/252371.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=ae765eee2381623c3de3763ab9085927",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Wirtz",
                overall: "89",
                time: "Liverpool",
                liga: "prl",
                pais: "DE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/256630.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=e41afe26976b4f812646c7f92de30d5a",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452",
            },
            {
                nome: "Musiala",
                overall: "88",
                time: "Bayern",
                liga: "bun",
                pais: "GB",
                uk: "inglaterra",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/256790.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=c5d95dbb9a19977cc918bd07b3ff40bd",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/1024px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png",
            },
            {
                nome: "Palmer",
                overall: "90",
                time: "Chelsea", // Cm ou Pe???
                liga: "prl",
                pais: "GB",
                uk: "inglaterra",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/257534.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=d2b72696872749b243674b0e47ec5848",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/c/cc/Chelsea_FC.svg/2048px-Chelsea_FC.svg.png",
            },
            {
                nome: "Bruno Fernandes",
                overall: "88",
                time: "Man United",
                liga: "prl",
                pais: "PT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/212198.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=9b766eabc815f59c492efe5e9938a0ad",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/b/b6/Manchester_United_FC_logo.png",
            },
            {
                nome: "Olmo",
                overall: "85",
                time: "Barcelona",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/244260.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=745507d828cc8f7a93fd2d70d1137665",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Szoboszlai",
                overall: "88",
                time: "Liverpool",
                liga: "prl",
                pais: "HU",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/236772.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=b2d41f440177e039f06ff7cd06afc2cb",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452",
            },
            {
                nome: "Brandt",
                overall: "84",
                time: "Dortmund",
                liga: "bun",
                pais: "DE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/212194.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=67134d1de4e1e38b9d769a5aabe09f02",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/2048px-Borussia_Dortmund_logo.svg.png",
            },
            {
                nome: "Fermin",
                overall: "87",
                time: "Barcelona",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/277179.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=0d8d5ced48ac0293af28a3399da0f752",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Yildiz",
                overall: "84",
                time: "Juventus",
                liga: "sra",
                pais: "TR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/277954.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=df4e3558dfd0f25341744c7d2ac0364c",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Juventus_FC_-_logo_black_%28Italy%2C_2020%29.svg",
            },
            {
                nome: "Isco",
                overall: "83",
                time: "Betis",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/197781.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=d0fad6688d0a4e01c34900e9bf876ff6",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/1/17/Real_Betis_Balompi%C3%A9.png",
            },
        ]


    },
    {
        posicao: "ponta", 

        jogadoresPosicao: [
            {
                nome: "Vinicius Jr",
                overall: "90",
                time: "Real Madrid",
                liga: "lal",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/238794.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=b98e1d00cf9c17fdf5229a66570db3b8",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Salah",
                overall: "91",
                time: "Liverpool",
                liga: "prl",
                pais: "EG",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/209331.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=44bb7084c36fa4a482aefd934b9f6138",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452",
            },
            {
                nome: "Dembele",
                overall: "91",
                time: "Paris",
                liga: "li1",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/231443.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=c8c538b60934760418d3028f62379d26",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png",
            },
            {
                nome: "Yamal",
                overall: "91",
                time: "Barcelona",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/277643.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=31f160080807862edeec76838bb33475",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Raphinha",
                overall: "91",
                time: "Barcelona",
                liga: "lal",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/233419.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=f76660878ef40dabefb44c5c30cde82c",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Saka",
                overall: "89",
                time: "Arsenal",
                liga: "prl",
                pais: "GB",
                uk: "inglaterra",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/246669.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=4c61724ceef0fb40b20759f33cc61ee8",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
            {
                nome: "Rodrygo",
                overall: "89",
                time: "Real Madrid",
                liga: "lal",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/243812.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=bea9b5d4eb112185ab71483530416233",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Estevao",
                overall: "87",
                time: "Chelsea",
                liga: "prl",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/76687.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=52390af5996a701c8eb2c9f51eeb4742",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/c/cc/Chelsea_FC.svg/2048px-Chelsea_FC.svg.png",
            },
            {
                nome: "Kvaratskhelia",
                overall: "88",
                time: "Paris",
                liga: "li1",
                pais: "GE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/247635.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=83e4a201be070649d359906f71428b0b",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png",
            },
            {
                nome: "Nico Williams",
                overall: "87",
                time: "Bilbao",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/256516.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=2211bc4db8ee86d98a21e0d8731e6135",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/90/Athletic_Club_de_Bilbao.png",
            },
            {
                nome: "Doue",
                overall: "86",
                time: "Paris",
                liga: "li1",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/271421.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=b5fc5823017e475926351b65203bee4c",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png",
            },
            {
                nome: "Foden",
                overall: "87",
                time: "Man City",
                liga: "prl",
                pais: "GB",
                uk: "inglaterra",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/237692.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=dccf16afe1d86308f9449518d79ead38",
                timeimg: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
            },
            {
                nome: "Leao",
                overall: "85",
                time: "Milan",
                liga: "sra",
                pais: "PT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/241721.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=5b707f64edadceaeb272a5f14f6305e6",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/1306px-Logo_of_AC_Milan.svg.png",
            },
            {
                nome: "Pulisic",
                overall: "86",
                time: "Milan",
                liga: "sra",
                pais: "US",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/227796.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=9e58f361d3f1fa79074a1979174f469a",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/1306px-Logo_of_AC_Milan.svg.png",
            },
            {
                nome: "Ferran",
                overall: "85",
                time: "Barcelona",
                liga: "lal",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/241461.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=988e1424b6c246dff323d191c188aebe",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Savinho",
                overall: "85",
                time: "Man City",
                liga: "prl",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/270409.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=2dee2787139281529d9105b984a9a1fa",
                timeimg: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
            },
            {
                nome: "Trossard",
                overall: "84",
                time: "Arsenal",
                liga: "prl",
                pais: "BE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/207421.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=6de04cca2b94a4711c3db6b8cad005b8",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
            {
                nome: "Antony",
                overall: "88",
                time: "Betis",
                liga: "lal",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa25/img/players/255475.png?fm=png&ixlib=java-2.1.0&verzion=2&w=512&s=28b11d927c11d2bc2443f3377a64cf8e",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/1/17/Real_Betis_Balompi%C3%A9.png",
            },
            {
                nome: "Doku",
                overall: "86",
                time: "Man City",
                liga: "prl",
                pais: "BE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/246420.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=5e694c541ae22e347b49d723ccc5f977",
                timeimg: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
            },
            {
                nome: "Brennan Johnson",
                overall: "84",
                time: "Tottenham",
                liga: "prl",
                pais: "GB",
                uk: "gales",
                foto: "https://cdn3.futbin.com/content/fifa25/img/players/251421.png?fm=png&ixlib=java-2.1.0&verzion=2&w=512&s=91c1c1599d38e1cc845f951ecc5bc033",
                timeimg: "https://images.seeklogo.com/logo-png/55/2/tottenham-hotspur-f-c-2024-logo-png_seeklogo-557792.png",
            },
            
        ]


    },
    {
        posicao: "atacante", 

        jogadoresPosicao: [
            {
                nome: "Mbappe",
                overall: "91",
                time: "Real Madrid",
                liga: "lal",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/231747.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=549887833fd0129cebcdc165751f69df",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Haaland",
                overall: "91",
                time: "Man City",
                liga: "prl",
                pais: "NO",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/239085.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=e617f2ec4ed6163e30dc0ab21fe5b586",
                timeimg: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
            },
            {
                nome: "Kane",
                overall: "91",
                time: "Bayern",
                liga: "bun",
                pais: "GB",
                uk: "inglaterra",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/202126.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=52d9c3a825b081d84e3f3285d281d854",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/1024px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png",
            },
            {
                nome: "Lewandowski",
                overall: "90",
                time: "Barcelona",
                liga: "lal",
                pais: "PL",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/188545.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=ffbe928e6e83dcff03517d52014a03df",
                timeimg: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1183px-FC_Barcelona_%28crest%29.svg.png",
            },
            {
                nome: "Martinez",
                overall: "90",
                time: "Inter",
                liga: "sra",
                pais: "AR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/231478.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=73524c512aec3281cc943f169cbbfc93",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/2048px-FC_Internazionale_Milano_2021.svg.png",
            },
            {
                nome: "Isak",
                overall: "87",
                time: "Liverpool",
                liga: "prl",
                pais: "SE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/233731.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=0e0201ff35c7a309d6441726f498a988",
                timeimg: "https://tmssl.akamaized.net//images/wappen/big/31.png?lm=1727873452",
            },
            {
                nome: "Julian Alvarez",
                overall: "90",
                time: "Atletico Madrid",
                liga: "lal",
                pais: "AR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/246191.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=f9a95eb6bf3cbffc8cb728d4091c60ca",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/1/19/AtleticoMadrid2017.png",
            },
            {
                nome: "Gyokeres",
                overall: "90",
                time: "Arsenal",
                liga: "prl",
                pais: "SE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/241651.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=997c15db93fac35305dad46c429d05ba",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
            {
                nome: "Lukaku",
                overall: "86",
                time: "Napoli",
                liga: "sra",
                pais: "BE",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/192505.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=84d44d07e059fe3369f6f8d710a32f4a",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/SSC_Napoli.svg/2048px-SSC_Napoli.svg.png",
            },
            {
                nome: "Lookman",
                overall: "87",
                time: "Atalanta",
                liga: "sra",
                pais: "NG",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/230899.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=1e68ecc5c493015bebbb6b288608ef8f",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Logo_Atalanta_Bergamo.svg/500px-Logo_Atalanta_Bergamo.svg.png",
            },
            {
                nome: "Sorloth",
                overall: "86",
                time: "Atletico Madrid",
                liga: "lal",
                pais: "NO",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/216549.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=6cfdae63addd45ff5e188b5b773b1dc5",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/1/19/AtleticoMadrid2017.png",
            },
            {
                nome: "Havertz",
                overall: "86",
                time: "Arsenal",
                liga: "prl",
                pais: "DE",
                foto: "https://cdn3.futbin.com/content/fifa25/img/players/235790.png?fm=png&ixlib=java-2.1.0&verzion=2&w=512&s=23f56117885e322bd2ca2a4520d1c831",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
            {
                nome: "Vlahovic",
                overall: "85",
                time: "Juventus",
                liga: "sra",
                pais: "RS",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/246430.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=59924bcc05e8b85da6a425af9119ff8d",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Juventus_FC_-_logo_black_%28Italy%2C_2020%29.svg",
            },
            {
                nome: "Endrick",
                overall: "82",
                time: "Real Madrid",
                liga: "lal",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/272505.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=a7d6576e540e823a6b28ca09bb331e25",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png",
            },
            {
                nome: "Morata",
                overall: "81",
                time: "Como",
                liga: "sra",
                pais: "ES",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/201153.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=d36c5ba4852d769a927509d704774ad1",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Logo_Como_1907_2019.png/500px-Logo_Como_1907_2019.png",
            },
            {
                nome: "Aubameyang",
                overall: "82",
                time: "Marseille",
                liga: "li1",
                pais: "GA",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/188567.png?fm=png&ixlib=java-2.1.0&w=162&s=f8bb06448a99d28dd1f6d97f860794fb",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Olympique_Marseille_logo.svg/960px-Olympique_Marseille_logo.svg.png",
            },
            {
                nome: "Dzeko",
                overall: "82",
                time: "Fiorentina",
                liga: "sra",
                pais: "BA",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/180930.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=b6ef206566c6e879a29e88e1c8ee88ac",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/ACF_Fiorentina_-_logo_%28Italy%2C_2022%29.svg/2048px-ACF_Fiorentina_-_logo_%28Italy%2C_2022%29.svg.png",
            },
            {
                nome: "Kolo Muani",
                overall: "82",
                time: "Tottenham",
                liga: "prl",
                pais: "FR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/237679.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=7ec4b2b757e137f13f567affb0873f2e",
                timeimg: "https://images.seeklogo.com/logo-png/55/2/tottenham-hotspur-f-c-2024-logo-png_seeklogo-557792.png",
            },
            {
                nome: "Gabriel Jesus",
                overall: "84",
                time: "Arsenal",
                liga: "prl",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/230666.png?fm=png&ixlib=java-2.1.0&verzion=1&w=162&s=29cd1a1e57c3ea618617445598b1e2d7",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
            {
                nome: "Martinelli",
                overall: "84",
                time: "Arsenal",
                liga: "prl",
                pais: "BR",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/251566.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=95b10ed8ddde7a2b0adc8d26197bd9cd",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/53/Arsenal_FC.svg/1743px-Arsenal_FC.svg.png",
            },
            {
                nome: "Francisco Conceicao",
                overall: "86",
                time: "Juventus",
                liga: "sra",
                pais: "PT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/261050.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=15bf72c3e82a640c580bb4826b36201b",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Juventus_FC_-_logo_black_%28Italy%2C_2020%29.svg",
            },
            {
                nome: "Goncalo Ramos",
                overall: "86",
                time: "Paris",
                liga: "li1",
                pais: "PT",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/256903.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=982fef01534895945e66d8094a9b9398",
                timeimg: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png",
            },
            {
                nome: "Nicolas Jackson",
                overall: "82",
                time: "Bayern",
                liga: "prl",
                pais: "SN",
                foto: "https://cdn3.futbin.com/content/fifa26/img/players/259197.png?fm=png&ixlib=java-2.1.0&verzion=1&w=512&s=477144b10ff713052916464d55420764",
                timeimg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/1024px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png",
            },
        ]


    }
]